### ISSUE TITLE
Port to Scala.js 0.6 and its new test interface

### ISSUE THREAD

**Issue by InTheNow** [rickynils/scalacheck#122]
Similar to [Port uTest to Scala.js 0.6](https://github.com/lihaoyi/utest/issues/44).

Release details are [on the Scala.Js forum](https://groups.google.com/forum/?fromgroups#!topic/scala-js/QMlQwSt4VS0)

**Comment by bblfish** [comment]
+1 for me on this.

**Comment by antonkulaga** [comment]
+1 for me on this.

I also want to point out that scalajs0.6 cross project can be used here to share sources

```
lazy val scalacheck = CrossProject.apply("scalacheck",new File("."),CrossType.Full).
  settings(sharedSettings: _*).
  jsSettings(
    libraryDependencies += "org.scala-js" %% "scalajs-test-interface" % scalaJSVersion
  ).
  jvmSettings(
    libraryDependencies ++= Seq(
      "org.scala-sbt" % "test-interface" % "1.0",
      "org.scala-js" %% "scalajs-stubs" % scalaJSVersion % "provided"
    )
  )

lazy val js = scalacheck.js
lazy val jvm  = scalacheck.jvm
```

**Comment by InTheNow** [comment]
Quick heads up that I've done an initial port to scalajs 0.6. It's working OK, but needs polishing before I can push for initial feedback, hope in next day or two. This is using RC1, so looks like we should be ready for the final 0.6 release ( that is a BIG one, btw).

In meantime, chats are on https://gitter.im/scala-js/scala-js and https://gitter.im/w3c/banana-rdf

**Comment by InTheNow** [comment]
Please see pull request #139, already reviewed by @srjd  and new commit based on review comments.

@srjd - many thanks (again) for your comprehensive review comments.
