### ISSUE TITLE
Create inbuilt Shrinks to match the inbuilt Generators

### ISSUE THREAD

**Issue by DomBlack** [rickynils/scalacheck#130]
I was building my Shrinks when I realised that even though scalacheck includes a generators for `Long`, `Double` etc it does not include Shrinks for them and thanks to the implicit ShrinkAny I did not release this.

I would assume if the library provided the Generators, it should also provide the Shrinks for those types.

**Comment by rickynils** [comment]
Not having a shrinker for `Long` is a glaring omission, I admit. I'll fix that.

In ScalaCheck 2, shrinkers will be more tightly tied to generators, btw.

**Comment by DomBlack** [comment]
Is it possible perhaps have custom shrinks give a warning if `ShrinkAny` get's implicitly called within them?

Although if in version 2 the plan is to tie shrinkers to generators that might not be required.

**Comment by DomBlack** [comment]
Just an FYI I'm implemented a semi complete generic numeric shrinker based on the original Int shrinker in the library. If you want I can issue a PR for that tomorrow replacing the original Int shrinker?

**Comment by rickynils** [comment]
Fixed in #135
