### ISSUE TITLE
destroySut is called before commands are finished in multithreaded environment

### ISSUE THREAD

**Issue by donnerpeter** [rickynils/scalacheck#138]
Sample code:

object HashMapCheck extends Commands {

  def main(args: Array[String]) {
    property(threadCount = 3).check
  }

  type State = Map[String, String]
  type Sut = util.HashMap[String, String]

  override def canCreateNewSut(newState: State, initSuts: Traversable[State], runningSuts: Traversable[Sut]): Boolean = true
  override def destroySut(sut: Sut): Unit = { println("destroy " + System.identityHashCode(sut)) }
  override def initialPreCondition(state: State): Boolean = state.isEmpty

  override def newSut(state: State) = {
    val result: util.HashMap[String, String] = new util.HashMap[String, String]()
    println("newSut " + System.identityHashCode(result));
    result
  }

  override def genInitialState: Gen[State] = const(Map())

  val mapKey: Gen[String] = for (c1 <- alphaChar) yield String.valueOf(c1)

  def genCommand(s: State): Gen[Command] = for (s1 <- mapKey; s2 <- arbitrary(arbString)) yield Put(s1, s2)

  def checkSize(sutKeys: util.Set[String], map: State): Boolean = {
    val stateKeys: util.Set[String] = setAsJavaSet(map.keySet)
    sutKeys == stateKeys
  }

  case class Put(key: String, value: String) extends Command {
    type Result = util.Set[String]
    override def run(sutMap: Sut): Result = {
      println("put " + System.identityHashCode(sutMap))
      sutMap.put(key, value)
      new util.HashSet(sutMap.keySet())
    }
    override def nextState(s: State): State = {
      val result = s + (key -> value)
      result
    }

    override def preCondition(state: State): Boolean = true

    override def postCondition(state: State, result: Try[Result]): Prop = {
      result.map(checkSize(_, nextState(state))) == Success(true)
    }
  }
}

Sample output:

newSut 1920387277
destroy 1920387277
put 1920387277
put 1920387277
put 1920387277
put 1920387277
put 1920387277
put 1920387277
put 1920387277
put 1920387277
.....

**Comment by dpolivaev** [comment]
Fixed in https://github.com/rickynils/scalacheck/pull/156

**Comment by rickynils** [comment]
#156 has been merged now.

**Comment by dpolivaev** [comment]
Please consider follow-up pull request https://github.com/rickynils/scalacheck/pull/160
