### ISSUE TITLE
Behavior of Gen.retryUntil

### ISSUE THREAD

**Issue by rvvincelli** [rickynils/scalacheck#145]
Hello, this is not really an issue but I thought it is easier and more visible to post it here rather than on the mailing list. 

I want to define a stateful generator, and since I cannot find anymore the constructor `Gen.Params => Option[T]` nor any other facility supporting in this (CMIIW) my pick to get things done is the `retryUntil` method. I want a unique generator, its defining property is that any value generated by it can be seen at most once.

The initial attempt is:
```scala
def unique[A](gen: Gen[A]): Gen[A] = {
    val generated: mutable.Set[A] = mutable.Set.empty
    gen.retryUntil { a =>
      if (!generated.contains(a)) {
        generated += a
        true
      }
      else false
    }
  }
```

Now the [`retryUntil`](https://github.com/rickynils/scalacheck/blob/1.12.2/src/main/scala/org/scalacheck/Gen.scala#L82) method verifies that the extraction satisfies the property, and if this is the case it returns a constant generator where this property is enforced again with `suchThat`. The generator above is a `None`-one because, not sure if I am expressing myself correctly here and if this is the cause, the property is "closed" and cannot therefore ever evaluate to true with respect to the mutable state `Set`. By using an auxiliary function which is exactly the same except than for the `suchThat(p)` instead the generator works, it is easy to test it by feeding it some small generator, you will see it exausts after a few samples. 

Now I just wanted to point out this possible issue in interpreting this call, discuss cases like this and see what do you think about it. Thanks,

**Comment by rickynils** [comment]
OK, it should maybe be noted in the documentation for `retryUntil` and `suchThat` that the provided test method must be side-effect free. There is no guarantee that the test will be executed only once. In fact, it has to be executed several times during the shrinking phase. In your example, when the test is executed a second time, for the same value of `a`, it will return false.

**Comment by rvvincelli** [comment]
#146

**Comment by rickynils** [comment]
#146 has been merged, closing this issue.
