### ISSUE TITLE
New release with latest JS impl

### ISSUE THREAD

**Issue by InTheNow** [rickynils/scalacheck#157]
The 1.12.2 release had a few minor issues that now seem to be fixed with the refactor to use the same code on JS/JVM - could this be published asx 1.12.3, please?

**Comment by InTheNow** [comment]
Hi- Scala.js 0.6.3 has been released that includes a fix for PermGen exceptions that have caused scalajs to be removed from the travis build. Also, a release of scaclatest for scalajs is expected, apparently 

Any chance of this, please?

**Comment by rickynils** [comment]
@InTheNow I have bumped the scalajs version now. It seems we still get PermGen exception in the Travis builds, but I haven't looked closer.

**Comment by InTheNow** [comment]
In addition to https://github.com/sjrd/scalacheck/commit/46f836798133333f3a417fb4e0300fc0923dbfa9, you might also want to cross ref with https://github.com/rickynils/scalacheck/pull/139 that might cover similar points.

**Comment by rickynils** [comment]
The Travis builds works fine with scala.js 0.6.3 now. I'll release ScalaCheck 1.12.3 soon.

**Comment by InTheNow** [comment]
Excellent!!

**Comment by rickynils** [comment]
ScalaCheck 1.12.3 has now been released, closing this issue.
