### ISSUE TITLE
implication operator not found

### ISSUE THREAD

**Issue by gt-tech** [rickynils/scalacheck#159]
val propMakeList = forAll { n: Int => ( (n >= 0 && n < 10000) ==> (List.fill(n)("").length == n) )}

results in warning in Scala IDE (and compilation error) that - value =⇒ is not a member of Boolean

ScalaCheck version - scalacheck_2.11-1.12.2
Scala Version - 2.11.6
scala-parser-combinators - 2.11.0-M4

**Comment by rickynils** [comment]
@gt-tech I think you need to add `import org.scalacheck.Prop.BooleanOperators` (or `import org.scalacheck.Prop._`)

**Comment by hzach** [comment]
I'm having the same problem. I tried the same example above with the explicit import of BooleanOperators. Intellij gives an error saying that the symbol `==>` cannot be resolved.

I'm using the same versions of scalaCheck and Scala as @gt-tech

**Comment by gt-tech** [comment]
I was able to resolve the issue, the code after implication operator needed to be enclosed in curly brackets, thanks @rickynils , I had wildcard import on Prop earlier.
