### ISSUE TITLE
Play + ScalaCheck + specs2: Missing or invalid dependency

### ISSUE THREAD

**Issue by zbeckman** [rickynils/scalacheck#162]
I'm trying to get ScalaCheck working with Play Framework (2.3.9).

After adding the specs2-scalacheck dependency:

	"org.specs2" %% "specs2-scalacheck" % "3.6" % "test",

I end up getting:

[error] missing or invalid dependency detected while loading class file 'JUnitRunner.class'.
[error] Could not access type DefaultSelection in package org.specs2.reporter,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic class path.)

It seems like this should be working but either there's a conflict with the latest Play framework, or I'm completely wrong on my installation steps... any help?

**Comment by rickynils** [comment]
Sorry, but this doesn't seem like an issue in ScalaCheck, which is not using `JUnitRunner` anywhere.
