### ISSUE TITLE
Test.scala fails to compile in scala.js

### ISSUE THREAD

**Issue by yawnt** [rickynils/scalacheck#164]
`Test.scala` (and at a first glance `Commands.scala` and maybe something else) depend on multiple `java.util.concurrent.*` classes, which are not available in Scala.js. This causes the compilation to fail with `linking errors`. 
From the look of it it seems like most of it is needed for parallelism, but I'm not familiar with the lib enough to figure out what I can remove and what not.
Any help would be appreciated!
thanks!

**Comment by rickynils** [comment]
I'm confused. ScalaCheck 1.12.2 has been released for scala.js: http://search.maven.org/#artifactdetails%7Corg.scalacheck%7Cscalacheck_sjs0.6_2.11%7C1.12.2%7Cjar

**Comment by rickynils** [comment]
OK, now I get it, ignore my confusion. This was fixed in 46f836798133333f3a417fb4e0300fc0923dbfa9
