### ISSUE TITLE
maxDiscarded problem in 1.12.3

### ISSUE THREAD

**Issue by cheeseng** [rickynils/scalacheck#168]
Hi all, 

We just discovered that upgrading from 1.12.2 to 1.12.3 breaks one of our test that depends on the behavior of maxDiscarded: 

```
it("ScalaCheck property that takes 6 args and generators, which fails, with default maxDiscarded set to 5") {

    // Hides the member
    implicit val generatorDrivenConfig = PropertyCheckConfig(maxDiscarded = 5)

    intercept[GeneratorDrivenPropertyCheckFailedException] {
      var i = 0
      val prop = forAll (famousLastWords, famousLastWords, famousLastWords, famousLastWords, famousLastWords, famousLastWords) { (a: String, b: String, c: String, d: String, e: String, f: String) =>
        i += 1
        (i > 6) ==> { 1 + 1 == (2) }
      }
      check(prop)
    }
  }
```

It is working correctly with 1.12.2, but not 1.12.3, we tried to look up for behavior change of maxDiscarded/discard in 1.12.3 release note but didn't get any, can we know what has changed in maxDiscarded/discard behavior from 1.12.2 -> 1.12.3?

Thanks in advanced for any help or pointer.

**Comment by rickynils** [comment]
@cheeseng Can you go into some more details on how the behavior differs for you between 1.12.2 and 1.12.3? Would it be possible to demonstrate it in a ScalaCheck-only scenario? The `maxDiscarded` parameter is not part of ScalaCheck, for example. Only `maxDiscardRatio`.

**Comment by cheeseng** [comment]
Hi @rickynils , thanks for replying, actually we did check last week and found out that the reason behind the failed tests is that maxDiscardRatio will still at least try minSuccessful of time, even if the maxDiscardRatio thresold has been reached, so we modified our tests to adapt to the mentioned behaviour and they're cool now.  :)

Sorry for making the noise, I'll close this issue.
