### ISSUE TITLE
Usefulness of org.scalacheck.Prop#check?

### ISSUE THREAD

**Issue by kevinmeredith** [rickynils/scalacheck#175]
I wrote a scalacheck test that called [org.scalacheck.Prop#check](https://scalacheck.googlecode.com/svn/artifacts/1.9/doc/api/org/scalacheck/Prop.html). I had figured that this method would've caused an assertion failure if the property did not hold. However, it did not.

```
object PersonSpecification extends Properties("Person" { 
  val prop: Prop = .... // omitted
}
```

```
class PersonTest extends FlatSpec {	
"Person#create with an age between 0 and Int.MaxValue" should "be valid" in {
		PersonSpecification.prop.check
	}
}
```

Running `sbt test` produced console output that indicated a test failure. However, sbt reported that the test had succeeded.

[org.scalacheck.Prop](https://scalacheck.googlecode.com/svn/artifacts/1.9/doc/api/org/scalacheck/Prop.html)'s docs explain `check`:
> Convenience method that checks this property and reports the result on the console.

I added the following change to the scalatest test in order for sbt to register the failed test as a true failure:

```
import org.scalatest.prop.Checkers._
    ...
    check(PersonSpecification.prop)
```

Would this test be more useful if it threw an Exception to indicate a test failure? Or, perhaps the documentation captures exactly what it does, and it should stay as-is?

Here's the full [thread](https://groups.google.com/forum/#!topic/scalacheck/UnDW6eXCuFw) from the Scalacheck Google Groups page.

**Comment by rickynils** [comment]
I think that the documentation can be improved, to point out that `Prop.check` and `Properties.check` only makes sense when you're running checks interactively in the Scala REPL. Otherwise you should use the sbt test runner (or the ScalaTest or specs integration).

Throwing an exception wouldn't make sense for ScalaCheck, since exceptions aren't used anywhere else to indicate test failures.

**Comment by rickynils** [comment]
Closing this, scaladoc has been updated.

**Comment by kevinmeredith** [comment]
Thank you for this fix (and the library)!
