### ISSUE TITLE
Stateful testing section of user guide not up to date?

### ISSUE THREAD

**Issue by statusfailed** [rickynils/scalacheck#183]
I tried to write some "stateful testing" code by following the [user guide](https://github.com/rickynils/scalacheck/wiki/User-Guide), but it doesn't seem to work.
I'm getting errors like the following when I try to compile:

    [error] Demo.scala:14: object creation impossible, since:
    [error] it has 5 unimplemented members.
    [error] /** As seen from object CounterSpecification, the missing signatures are as follows.
    [error]  *  For convenience, these are usable as stub implementations.
    [error]  */  
    [error]   def canCreateNewSut(newState: CounterSpecification.State,initSuts: Traversable[CounterSpecification.State],runningSuts: Traversable[CounterSpecification.Sut]): Boolean = ??? 
    [error]   def destroySut(sut: CounterSpecification.Sut): Unit = ??? 
    [error]   def genInitialState: org.scalacheck.Gen[CounterSpecification.State] = ??? 
    [error]   def initialPreCondition(state: CounterSpecification.State): Boolean = ??? 
    [error]   def newSut(state: CounterSpecification.State): CounterSpecification.Sut = ??? 
    [error] object CounterSpecification extends Commands {
    [error]        ^   

I guess I'm missing these "[destroy/new/canCreateNew]Sut" methods, but I can't figure out what they're for- here's the code I'm trying to run with "sbt test":

    import org.scalacheck.Properties                                                                                                                   
    import org.scalacheck.Prop.forAll
    import org.scalacheck.commands._
    import org.scalacheck._
    class Counter {
      private var n = 0
      def inc = n += 1
      def dec = n -= 1
      def get = n
      def reset = n = 0
    }
    object CounterSpecification extends Commands {
      val counter = new Counter
      case class State(n: Int)
      def initialState() = {
        counter.reset
        State(counter.get)
      }
      case object Inc extends Command {
        def run(s: State) = counter.inc
        def nextState(s: State) = State(s.n + 1)
      }
      def genCommand(s: State): Gen[Command] = Gen.oneOf(Inc, Inc)
    }

Is the documentation out of date, or am I just making a mistake here?

**Comment by rickynils** [comment]
Ah, the documentation could very well be out of sync with the implementation. I'll look into it when I get time.

**Comment by joshlemer** [comment]
+1

**Comment by rickynils** [comment]
@statusfailed @joshlemer 0e6f9f4 should fix this issue, I hope. Please check out https://github.com/rickynils/scalacheck/blob/master/doc/UserGuide.md

**Comment by joshlemer** [comment]
Thanks @rickynils
