### ISSUE TITLE
Custom number of runs per property

### ISSUE THREAD

**Issue by sid-kap** [rickynils/scalacheck#187]
I'm using scalacheck with sbt. When I run the `test` command in sbt, Scalacheck, by default, generates 100 test cases for each `Prop` in all `Properties` classes in my test path.

Can we add a feature so that I can specify minSuccessfulTests for each Prop in my source code? This would be useful so that I can run fewer tests for tests that take longer to run.

What I have in mind is an annotation that I can apply to either my Properties class or each property block in my Properties class, specifying minSuccessfulTests for the appropriate tests.

I think this would be easy to implement, so I wouldn't mind implementing this if you guys like the idea.

**Comment by rickynils** [comment]
This should be possible to add in ScalaCheck 2. Adding it to the current implementation would probably be too involved.

**Comment by sid-kap** [comment]
I'm not sure that I want to wait until ScalaCheck 2.
I think I'll take a stab at this and see if we can get this working without changing the current implementation too much?

**Comment by rickynils** [comment]
PR #188 has been merged.
