### ISSUE TITLE
Understanding the isExhausted formula is too exhausting

### ISSUE THREAD

**Issue by bvenners** [rickynils/scalacheck#192]
Hi Rickard,

We made a change to ScalaTest that has caused some pain for users using our 3.0 milestone releases, and we think it may best be addressed by revisiting this line of code in ScalaCheck:

https://github.com/rickynils/scalacheck/blob/master/src/main/scala/org/scalacheck/Test.scala#L292

What I wanted to do in ScalaTest in 3.0 was dial down the default minSuccessfulTests from 100 to 10. (So we did that.) The reason that I thought that will be better is that when people use ScalaTest, they run tests over and over again both on developer desktops and on continuous integration servers. Once freshly written code is working, those tests are often run for years to catch regressions, and they almost never fail. So the default of 100 ends up just wasting a lot time, electricity, and money, releasing greenhouse gasses that warm the planet with no benefit to show of improved software quality. In other words, even with a default minSuccessfulTests of 10, you'll get 100 trials after running your test suite 10 times, which is often done in just one day. I think that's fast enough for regression testing, and what I felt is that the defaults in ScalaTest should be ones that make sense for that kind of regression testing.

Ok, so what that changes is that sometimes people use a generator that discards quite a large percentage of the generated values, because it is quicker for them to do that than write a new generator that is more accurate. And sometimes, the first 11 values generated turn out to be all discarded, whereas one of the first 101 values would likely not have been. The formula ScalaCheck uses for determining exhaustedness seems to short circuit in that situation. If we set minSuccessfulTests to 10 and maxDiscardRatio to 5.0, then users expect it would not give up until at least 50 evaluations were discarded, but it gives up after 11. To see an exact use case with numbers (based on a user issue), see the bottom of this issue:

https://github.com/scalatest/scalatest/issues/661

I would be happy to suggest a change to the formula with a PR, but I don't know exactly why it is the way it is now. It may be as simple as adding one more clause to the Boolean expression that says that plain old d is greater than minSuccessfulTests * maxDiscardRatio. 

    n+d > minSuccessfulTests && 1+workers*maxDiscardRatio*n < d && (d > minSuccessfulTests * maxDiscardRatio)

But I'm not sure. I'd be interested in understanding the formula better.

Thanks.

Bill

**Comment by rickynils** [comment]
The scaladocs on `maxDiscardRatio` say this:

```
The maximum ratio between discarded and passed tests allowed before ScalaCheck gives up and discards the property. At least minSuccesfulTests will always be run, though.
```

The problem you have is that the current implementation checks if `maxDiscardRatio` has been violated after each test run. If the very first test is discarded, we already have an infinitely high discard ratio. The `n+d > minSuccessfulTests` condition is there to protect against such cases. However, when `minSuccessfulTests` is small (as in your case), it doesn't help all that much (as you've described above).

To me, it is not immediately clear that `minSuccessfulTests=10` and `maxDiscardRatio=5.0` should allow up to 60 evaluations (I mean, we could even continue testing, maybe sometime we find enough passing tests to get the discard ratio down...). But maybe it is the reasonable thing to do.

So, I think we could switch `isExhausted` to just your condition:

```
d > minSuccessfulTests * maxDiscardRatio
```

Now, that `d` is per worker, so the above condition will probably create extra discard evaluations (beyond `maxDiscardRatio`) when `workers > 1`. A less excessive implementation would be:

```
d * workers > minSuccessfulTests * maxDiscardRatio
```

But that assumes all workers have the same pass/discard ratio, which is not a safe assumption.

I have implemented this in c358554385362f0f774409d7d69e8cb3874fcab5. If you think it looks OK (especially if the changed scaladoc makes sense), I'll merge it to master.

A side-note: The test for this (in https://github.com/rickynils/scalacheck/blob/c358554385362f0f774409d7d69e8cb3874fcab5/jvm/src/test/scala/org/scalacheck/TestSpecification.scala#L65) is an example of when ScalaCheck really shines. I tested `d * workers > minSuccessfulTests * maxDiscardRatio` and other variations, and ScalaCheck immediately came up with weird combinations of `workers`, `minSuccessfulTests` and `maxDiscardRatio` that falsified the property.
