### ISSUE TITLE
New release with fixes

### ISSUE THREAD

**Issue by ghost** [rickynils/scalacheck#195]
Hi,

There is a [cats workaround](https://github.com/non/cats/blob/master/tests/src/test/scala/cats/tests/CatsSuite.scala#L58)  for https://github.com/rickynils/scalacheck/pull/170 and the issue of GeneratorDrivenPropertyCheck failing on Scala-js 2.10 (https://github.com/scalatest/scalatest/issues/661 and https://github.com/rickynils/scalacheck/issues/192) that have both been fixed and merged to master.

Please can a new release incorporate these, please? The later in particular is causing build failures, eg https://github.com/non/cats/pull/551.

**Comment by xuwei-k** [comment]
+1

**Comment by ceedubs** [comment]
:+1: I've been eagerly awaiting this since the introduction of `Cogen`. Is there any way that I can help move this along?

**Comment by rickynils** [comment]
@ceedubs You can keep nagging me. I'm not kidding you, it actually helps. I will try to dedicate tomorrow to ScalaCheck, so hopefully we should see a release soon. I don't think there are any showstoppers, the only reason this has taken so long is the combination of me having too much to do and being lazy.

**Comment by ceedubs** [comment]
@rickynils sounds great. Thank you!

**Comment by InTheNow** [comment]
@rickynils Am I right in saying that this is fully covered by 1.3.x? If, so this can now be closed.

**Comment by non** [comment]
Yes, I think the 1.13.x releases address this issue, and it can be closed.
