### ISSUE TITLE
Publish 1.12.5 for Scala 2.12.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [rickynils/scalacheck#198]
(I see 1.11.6 for 2.12.0-M3 on Maven Central, but not 1.12.5)

The Scala team would be interested in hearing if you encounter any trouble with M3.

**Comment by rickynils** [comment]
Thanks for reminding me. This had just slipped my mind. I've published 1.12.5 for Scala 2.12.0-M3 now.

@etorreborre @pchiusano

**Comment by etorreborre** [comment]
Thanks @rickynils.
