### ISSUE TITLE
Problem when composing `Gen[String]`

### ISSUE THREAD

**Issue by jvican** [rickynils/scalacheck#203]
__What am I doing?__
I am building a  _TOML parser_. I want to check strings of unparsed `Long`s that may have underscores between them (following the standard). This is my approach:
```scala
object NumbersTomlGen {
  def intersperse(x: String, sep: String) =
    x.toCharArray.mkString(sep)

  // Prints only for debugging
  val validLongGen: Gen[String] = for {
      l <- Gen.posNum[Long]
      sign <- Gen.oneOf(signChars)
      us <- Gen.oneOf(List("", "_"))
    } yield {
        println(s"Num $l, sign $sign, us $us"); 
        val a = sign + intersperse(l.toString, us);
        println(a);
        a
      }
}
class NumbersTomlSpec extends PropSpec with PropertyChecks with Matchers 
                                          with NumbersTomlGen with TomlParser {
  import Toml._
  property("parse integers") {
    forAll(validLongGen) {
      s: String =>
        println(s"Trying to parse $s to Long")
        val expected = Success(Integ(s.toLong), s.length)
        elem.parse(s) shouldBe expected
    }
  }
```
__Problem__
I get an error because my `Gen[String]` is returning an empty String and a NumberFormatException is thrown since an empty string cannot be converted to Long. Why an empty string? I have no idea. In theory, a `Gen[Long]` should always return a value, which is a non-empty string. If you execute the above code, you will see the following prints:
```
Num 1, sign -, us _
Result -1
Trying to parse -1 to Long
Num 2, sign +, us _
Result +2
Trying to parse +2 to Long
Num 3, sign , us _
Result 3
Trying to parse 3 to Long
Num 1, sign , us _
Result 1
Trying to parse 1 to Long
Num 2, sign -, us _
Result -2
Trying to parse -2 to Long
Num 3, sign -, us _
Result -3
Trying to parse -3 to Long
Num 1, sign , us 
Result 1
Trying to parse 1 to Long
Num 5, sign -, us 
Result -5
Trying to parse -5 to Long
Num 3, sign +, us 
Result +3
Trying to parse +3 to Long
Num 4, sign -, us 
Result -4
Trying to parse -4 to Long
Num 5, sign -, us _
Result -5
Trying to parse -5 to Long
Num 9, sign +, us 
Result +9
Trying to parse +9 to Long
Num 2, sign -, us 
Result -2
Trying to parse -2 to Long
Num 12, sign +, us _
Result +1_2
Trying to parse +1_2 to Long
Trying to parse +1 to Long
Trying to parse _2 to Long
Trying to parse _ to Long
Trying to parse  to Long
```
Please, focus on the 5 last lines. As I see it, the final generated value is being split __somehow__ into 5 different strings; one of them is the empty `String`. I am expecting to get only the value `+1_2`, which is a valid `Long`. But why am I getting the other bits?

**Comment by rickynils** [comment]
This is probably because your parser fails for the string `+1_2` (`elem.parse(s) shouldBe expected` fails). ScalaCheck will then attempt to find a smaller variant of `+1_2` that also fails (the shrinking feature).

Is there a way to instruct ScalaTest to print out the non-shrunk test result? ScalaCheck does it by default, but I don't know about ScalaTest.

You could add a print statement that shows what the result of `elem.parse` really is.

**Comment by jvican** [comment]
Oh yes, you are right. I thought that `ScalaCheck` emitted a warning, but as you pointed out, this is not the default behavior for the `Scalatest` compatibility. Maybe we should add it.
Thanks.

**Comment by rickynils** [comment]
Closing this, as it's not an issue in ScalaCheck
