### ISSUE TITLE
Publish 1.12.5 for scala-js 0.6 and scala 2.12.0-M3

### ISSUE THREAD

**Issue by cheeseng** [rickynils/scalacheck#204]
Hi Rickard, 

Is it possible to publish 1.12.5 scala-js version for scala 2.12.0-M3?  scalacheck_sjs0.6_2.12.0-M2 seems to be available already but not scalacheck_sjs0.6_2.12.0-M3.

FYI Here's a related issue on ScalaTest: 

https://github.com/scalatest/scalatest/issues/749

Thanks.  :)

**Comment by ngbinh** [comment]
:+1:

**Comment by rickynils** [comment]
@cheeseng @ngbinh I've released it now. It should hopefully be on maven central soon. Thank you for reminding me!
