### ISSUE TITLE
Why JSExport Properties?

### ISSUE THREAD

**Issue by japgolly** [rickynils/scalacheck#208]
Hello. I just started creating a cross JVM/JS compilation patch for Scalaz, and ran into a problem: In one file, there are many instances of them creating `Properties` like `new Properties(...)` [example](https://github.com/scalaz/scalaz/blob/series/7.2.x/scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala#L566-L567) which fails JS compilation because ScalaChecks `Properties` class has `@JSExportDescendentObjects @JSExportDescendentClasses`.

Why is `Properties` exported? Is it an oversight or misunderstanding? The reason you'd do that would be so that `Properties` can be accessed directly by someone writing native JS code. It isn't necessary for anyone writing Scala.JS.

**Comment by japgolly** [comment]
FYI I worked around it by doing this:
https://github.com/japgolly/scalaz/commit/85c7b3a8a86b5b39385c8bb51e6a9f65272b0eea

**Comment by rickynils** [comment]
@japgolly This could very well be a misunderstanding from my side (as I'm no ScalaJS-expert). But simply removing the exports doesn't work:

```
> project js
[info] Set current project to scalacheck (in build file:scalacheck/)
> test
[info] Compiling 1 Scala source to scalacheck/js/target/scala-2.11/classes...
[info] Compiling 3 Scala sources to scalacheck/js/target/scala-2.11/classes...
[info] Compiling 7 Scala sources to scalacheck/js/target/scala-2.11/test-classes...
[info] Fast optimizing scalacheck/js/target/scala-2.11/scalacheck-test-fastopt.js
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) TypeError: Cannot read property 'MathSpec' of undefined
[error] Total time: 11 s, completed Nov 30, 2015 9:40:43 AM
```

**Comment by japgolly** [comment]
Woah, what's going on I wonder... I'm going to be away from code for a few weeks *(thank you Universe)* but I'd like to have a look at this later when I come back. If nothing else, I'd at least like to learn why this is needed if it is (because from my understanding it shouldn't be).

**Comment by rickynils** [comment]
@japgolly Did you find out anything about this?

**Comment by japgolly** [comment]
Sorry @rickynils, I haven't touched this and wouldn't have the time for at least another 2 months.
I'll stop being a nuisance and close this.
