### ISSUE TITLE
Runtime Exception with scalacheck 1.13.0

### ISSUE THREAD

**Issue by kamilkloch** [rickynils/scalacheck#217]
After updating scalacheck from `1.12.5` to `1.13.0` some tests (`scalatest 2.2.6`) throw the following exception:

```
An exception or error caused a run to abort: Implementing class 
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
```

**Comment by rickynils** [comment]
ScalaCheck 1.13.x is not binary compatible with 1.12.x, so I expect you'd have to rebuild ScalaTest.

**Comment by aappddeevv** [comment]
I'm getting error now as well. I have rebuilt. Using with scalatest 3.0.0-M15 on the jvm. Scalacheck 1.13.0. I commented out all my tests and its not related to any of the test per se. Here's my test class definition:

```scala
class VNodeSpec extends FlatSpec
    with Matchers
    with OptionValues
    with prop.PropertyChecks {
```

**Comment by dnvriend** [comment]
I have the same problem:  `java.lang.IncompatibleClassChangeError`
setup 1: (problem) scala 2.11.7, sbt 0.13.9, scalatest 3.0.0-M15, scalacheck 1.13.0,
setup 2: (problem) scala 2.11.7, sbt 0.13.9, scalatest 2.2.6, scalacheck: 1.13.0
setup 3: (works): scala 2.11.7, sbt: 0.13.9, scalatest: 3.0.0-M15, scalacheck: 1.12.5
setup 4: (works): scala 2.11.7, sbt 0.13.9, scalatest 2.2.6, scalacheck 1.12.5

**Comment by dabd** [comment]
I am facing exactly the same problem as dnvriend.  Any solution for using the latest releases of scalatest and scalacheck?

**Comment by rickynils** [comment]
All current releases of ScalaTest (2.2.6, 3.0.0 etc) are built against ScalaCheck 1.12.1 (see https://github.com/scalatest/scalatest/blob/master/project/scalatest.scala#L134). Therefore, there are no guarantees that you can simply swap out ScalaCheck 1.12.x for 1.13.y. ScalaCheck only maintains binary compatibility within the same minor version series (1.12.1, 1.12.2, 1.12.3 etc).

I don't know if there are some sbt/maven magic that can be used to encode this dependency within ScalaTest.

cc @bvenners

**Comment by rickynils** [comment]
cc @fommil

**Comment by fommil** [comment]
Ah.

**Comment by dportabella** [comment]
> All current releases of ScalaTest (2.2.6, 3.0.0 etc) are built against ScalaCheck 1.12.1 (see https://github.com/scalatest/scalatest/blob/master/project/scalatest.scala#L134). Therefore, there are no guarantees that you can simply swap out ScalaCheck 1.12.x for 1.13.y. ScalaCheck only maintains binary compatibility within the same minor version series (1.12.1, 1.12.2, 1.12.3 etc).

The ScalaTest documentation has at least two pages that explain how to use ScalaCheck:
http://www.scalatest.org/user_guide/generator_driven_property_checks
http://www.scalatest.org/user_guide/writing_scalacheck_style_properties

It would be good to mention this version requirement in this documentation.
