### ISSUE TITLE
Release against 2.12.0-M3-dc9effe

### ISSUE THREAD

**Issue by retronym** [rickynils/scalacheck#225]
Hi @rickynils!

As part of our 2.12 development, we're just about the switch to the [new encoding of traits](https://github.com/scala/scala/pull/5003) which is binary incompatible. To bootstrap our way through this change, we've released a Scala [version 2.12.0-M3-dc9effe](https://oss.sonatype.org/#nexus-search;gav~~~2.12.0-M3-dc9effe~~), which we will use as the new reference compiler until the release of 2.12.0-M4.

Our binaries will be in Maven Central within a few hours, but can be used immediately from [Sonatype OSS](https://oss.sonatype.org/content/repositories/releases) in SBT with:

```
> set resolvers += Opts.resolver.sonatypeReleases
```

Could you please release `"org.scalacheck" % "scalacheck_2.12.0-M3-dc9effe % "1.11.6"` against this build? That will allow us to update the Scala build to use `2.12.0-M3-dc9effe` while still being able to run our Scalacheck tests.

Note: during the release of 2.12.0-M3-dc9effe, we built our own copy of `scalacheck_2.12.0-M3-dc9effe`, but we only published this to an internal repository. So we don't anticipate any problems getting Scalacheck to build here.

**Comment by rickynils** [comment]
@retronym The release should be up now!

**Comment by retronym** [comment]
Thanks!
