### ISSUE TITLE
Create arbTuple1

### ISSUE THREAD

**Issue by nrinaudo** [rickynils/scalacheck#228]
I know this sounds silly, but I have some tests which run for any arity of tuples, including 1, and it was surprising to find that, given `A: Arbitrary`, there was no implicit `Arbitrary[Tuple1[A]]`.

I'd be happy to contribute the one-liner if there's any interest in having that be part of scalacheck.

**Comment by xuwei-k** [comment]
https://github.com/rickynils/scalacheck/blob/1.13.0/src/main/scala/org/scalacheck/ArbitraryArities.scala#L102-L108 ?

**Comment by nrinaudo** [comment]
Ah. I'm still on 1.12.5, which doesn't have it, and I didn't realise it was implemented for 1.13.0. My apologies.
