### ISSUE TITLE
release scalacheck_sjs0.6_2.12.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [rickynils/scalacheck#235]

**Comment by rickynils** [comment]
I've now released ScalaCheck 1.13.1, both JVM and JS versions. Built with Scala 2.10, 2.11 and 2.12.0-M4.

**Comment by xuwei-k** [comment]
Could you please release `"scalacheck_sjs0.6_2.12.0-M4" % "1.12.5"` ?

**Comment by rickynils** [comment]
@xuwei-k Done. Should be on its way to Maven now. Thanks for reminding me!
