### ISSUE TITLE
Shrinking ignores valid input specified via Gen and uses values outside of the test case!!

### ISSUE THREAD

**Issue by markehammons** [rickynils/scalacheck#237]
I'm trying to test a class with scalacheck using the following properties:
```scala
val rangeGenInt = for {
	low <- Gen.choose(Int.MinValue,Int.MaxValue/10)
	high <- Gen.choose(low + 1, low + 1000)
	step <- Gen.choose(1,math.min((high - low + 1) / 2, 50))
} yield (low,step,high)

property("Parseable[List[Int]].strTo") = Prop.forAll(rangeGenInt) { case (low,step,high) =>
	ev_SetInt.strTo(s"$low|$step|$high") == (low to high by step).toList
}
```

The test keeps failing because for some reason 0 is chosen as a value for step even though my arbitrary declaration explicitly forbids 0 as a valid input (a 0 step on a range makes for an infinite range). Why is this happening, and how can I avoid this problem in the future? 

### error text: 
```
[info] ! Parseable type tests.Parseable[List[Int]].strTo: Exception raised on property evaluation.
[info] > ARG_0: (0,0,0)
[info] > ARG_0_ORIGINAL: (-755618167,253977916,674232698)
[info] > Exception: java.lang.IllegalArgumentException: requirement failed
```

### edit: 

This code works:
```scala
property("Parseable[List[Int]].strTo") = Prop.forAll(rangeGenInt) { case (low,step,high) =>
	ev_SetInt.strTo(s"$low|$step|$high").toSet == (low to high by step).toSet
}
```

However, it was extremely difficult to discover this because the shrinking that occured after that initial failure was ignoring the settings i had put for the variables (high > low, step > 0). Can you make sure that shrinking only tries values that were in the original generators?

**Comment by ceedubs** [comment]
Did you mean for `Prop.forAll(rangeGenDouble)` to be `Prop.forAll(rangeGenInt)`?

**Comment by ceedubs** [comment]
Separately, you might want to change your generator to not use `Arbitrary.arbitrary[Int].suchThat`. This will likely generate a lot of ints outside the desired range and then discard them, which will slow your tests down a lot (and may end up producing errors about discarding too many values). When possible, it's usually best to make the generator produce values within the desired range without depending on filtering.

**Comment by markehammons** [comment]
@ceedubs: I copied the wrong bit of code, copied the right one and double checked that I'm still having the trouble. 

I've tried using Gen.choose, but I get the same results:

```[info] ! Parseable type tests.Parseable[List[Int]].strTo: Exception raised on property evaluation.
[info] > ARG_0: (0,0,0)
[info] > ARG_0_ORIGINAL: (-755618167,253977916,674232698)
[info] > Exception: java.lang.IllegalArgumentException: requirement failed
```

As you can see the requirement failing is "step != 0". I specifically set step to be between (math.abs(high-low)/10) +  1, which should mean the bottom bound to choose from is > 0, but it keeps choosing 0 as a valid input for step.

**Comment by markehammons** [comment]
I changed my code to use ```Gen.oneOf(((math.abs(high-low)/10) + 1) until (math.abs((high - low)/2) + 1))``` and added some println statements to see what was being generated and chosen. The generator generates proper values but still puts 0 as an argument sometimes!? 

```
13007736
65038678
34164467
61789312
308946556
185039815
186873112
934365559
237512986
[info] ! Parseable type tests.Parseable[List[Int]].strTo: Exception raised on property evaluation.
[info] > ARG_0: (0,0,0)
[info] > ARG_0_ORIGINAL: (-2084351997,237512986,-215620878)
[info] > Exception: java.lang.IllegalArgumentException: requirement failed
```

**Comment by markehammons** [comment]
Using ==> to make sure step, low, and high are all valid helps a ton. So it turns out this code of mine had an error, I should have compared two sets, instead of two lists since the range function and my parser creates the same values, but not in exactly the same order (which I don't really care about). The above test works when I switch to sets even when I eliminate the ==> operator.

**Comment by rickynils** [comment]
@markehammons Yeah, as you've noticed, the shrinker is not perfect. It can come up with values outside the original range of generated, because the the generators and shrinkers are not aware of each other. The shrinker only looks at the type of the generated value when it decides on how to simplify it. This is an implementation limitation that hopefully will be solved in a future version of ScalaCheck.

The thing to remember, though, is that the shrinker is only activated when a property is falsified in the first place, with non-shrunk values. So, even though the final shrunk value might confuse you, it is caused by an actual error in your implementation and/or specification.
