### ISSUE TITLE
arbBigDecimal causing Underflow (ArithmeticException)

### ISSUE THREAD

**Issue by muhuk** [rickynils/scalacheck#246]
Sorry for the sloppy report. I'll flesh it out later once I find the time.

I am consistently getting failures like this:

    ArithmeticException was thrown during property evaluation.
      Message: Underflow
      Occurred when passed generated values (
    
      )

(Note that `generated values` is empty.)

I can run my tests if I replace this expression:

    Arbitrary.arbBigDecimal.arbitrary

With this:

    Gen.oneOf(BigDecimal(1.0), BigDecimal(2.0), BigDecimal(3.0))

**Comment by non** [comment]
@muhuk Can you paste a bit more about this error? I'm not sure how to reproduce (and fix) this issue otherwise.

**Comment by muhuk** [comment]
Here is a complete test:

```scala
import org.scalacheck.Arbitrary
import org.scalacheck.Gen
import org.scalatest.Finders
import org.scalatest.WordSpec
import org.scalatest.prop.GeneratorDrivenPropertyChecks

class ArbBigDecimalUnderflow extends WordSpec with GeneratorDrivenPropertyChecks {
  val genBigDecimal = Arbitrary.arbBigDecimal.arbitrary

  "this one should fail" in {
    forAll(Gen.zip(genBigDecimal, genBigDecimal)) {
      case (a, b) ⇒ assert(a + b == b + a)
    }
  }
}
```


I am using:

- scala 2.11.8
- scalatest 2.2.6
- scalacheck 1.13.2

Any other specifics I can provide?

**Comment by non** [comment]
That's great, thanks!

**Comment by muhuk** [comment]
You're welcome.

**Comment by non** [comment]
@muhuk So my sense is that the `Gen[BigDecimal]` instances ScalaCheck uses right now are basically busted. They generate numbers so big that it's really difficult to do anything with them. For example, it's not clear what anyone is going to do with `9E+1054820097`.

What's worse is that the default generic shrinking code will naïvely divide by 2 to make the numbers small enough to work with. Trying to reach `1e-5` by repeatedly dividing `9E+1054820097` by `2` is not going to be a winning strategy.

In my own code I usually roll my own `Gen[BigDecimal]` instances (often created from a `Double` or similar). I think the right way to fix this is to change how ScalaCheck generates these values to make them at least semi-tractable to work with.

What do you think @rickynils?

**Comment by non** [comment]
(The subtext here is that when I tried to run the given example I didn't get an underflow, but my code just hung.)

**Comment by muhuk** [comment]
> (The subtext here is that when I tried to run the given example I didn't get an underflow, but my code just hung.)

This is interesting, because I've run it a few times and it underflowed every time, without hangs.

**Comment by non** [comment]
Hm, strange. Do you think you could arrange to catch the exception and print a stack trace? I'm happy to take a look at that, I just can't seem to produce one myself.

**Comment by muhuk** [comment]
I've let it run for 9 minutes, it hangs as you say.

Here's the entire output:

    Run starting. Expected test count is: 1
    ArbBigDecimalUnderflow:

My guess is it's a difference between JRE's or something like that.

**Comment by non** [comment]
I'm going to open an issue around creating more reasonable `BigDecimal` values, and link it with this one.

**Comment by muhuk** [comment]
Thanks @non . Since neither of us can reproduce it now, I'm closing this.

**Comment by muhuk** [comment]
Just confirming this solves my issue.
