### ISSUE TITLE
Release 1.13.2

### ISSUE THREAD

**Issue by julien-truffaut** [rickynils/scalacheck#250]
Would it be possible to get a patch release with recent changes? I am particularly interested by https://github.com/rickynils/scalacheck/pull/242

**Comment by rickynils** [comment]
Sure, I'll try to get that done tomorrow...

**Comment by julien-truffaut** [comment]
Thanks!

**Comment by rickynils** [comment]
@julien-truffaut 1.13.2 should be available now!

**Comment by julien-truffaut** [comment]
@rickynils awesome it works!
