### ISSUE TITLE
Generators in a for-expression not working as expected

### ISSUE THREAD

**Issue by cokleisli** [rickynils/scalacheck#253]
The following generators should only produce values greater than 0. However, as can be seen the output, this is not the case. Is this a bug?

  implicit lazy val genUnequalIntPairs = for {
    i <- Gen.choose(1,1000)
    j <- Gen.choose(1,1000)
    if (i < j)
  } yield (i,j)

  val kk = Prop.forAll (genUnequalIntPairs)  {
    case (x,y) => {
      println("x =" + x + ", y =" + y)
      x == y
    }
  }

  kk.check

x =444, y =972
x =0, y =972
x =0, y =0
x =0, y =486
x =0, y =0
x =0, y =243
x =0, y =0
x =0, y =122
x =0, y =0
x =0, y =61
x =0, y =0
x =0, y =31
x =0, y =0
x =0, y =16
x =0, y =0
x =0, y =8
x =0, y =0
x =0, y =4
x =0, y =0
x =0, y =2
x =0, y =0
x =0, y =1
x =0, y =0
! Falsified after 0 passed tests.
> ARG_0: (0,1)
> ARG_0_ORIGINAL: (444,972)
Empty test suite.

**Comment by nsengupta** [comment]
Application of suchThat doesn't work:
```
implicit lazy val genUnequalIntPairs = for {
      i <- Gen.choose(1,1000).suchThat(_ > 0)
      j <- Gen.choose(i+1,1000).suchThat(_ > 0)
      if (i < j)
    } yield (i,j)
    
    val kk = forAll (genUnequalIntPairs)  {
      case (x,y) => println("x =" + x + ", y =" + y)
        x == y
    }
    
    kk.check
```

This is one random output.

```
    x =536, y =730
    x =0, y =730
    x =0, y =0
    x =0, y =365
    x =0, y =0
    x =0, y =183
    x =0, y =0
    x =0, y =92
    x =0, y =0
    x =0, y =46
    x =0, y =0
    x =0, y =23
    x =0, y =0
    x =0, y =12
    x =0, y =0
    x =0, y =6
    x =0, y =0
    x =0, y =3
    x =0, y =0
    x =0, y =2
    x =0, y =0
    x =0, y =1
    x =0, y =0
    ! Falsified after 0 passed tests.
    > ARG_0: (0,1)
    > ARG_0_ORIGINAL: (536,730)
    res0: Unit = ()
```

**Comment by nsengupta** [comment]
Moving to Scalacheck 1.13.1 (earlier examples ran under Scalacheck 1.12.x), the observations are:
implicit lazy val genUnequalIntPairs = for {
      i <- Gen.choose(1,1000)
      j <- Gen.choose(1,1000)
      if (i < j)
    } yield {
      (i,j)
    }
    
    val kk = forAll(genUnequalIntPairs)  {
      case (x,y) => println("x =" + x + ", y =" + y)
        x < y
    }
    
    kk.check

produces
x =56, y =752
    x =395, y =532
    x =468, y =828
    x =326, y =749
    x =203, y =973
    x =294, y =393
    x =589, y =975
    x =44, y =75
    x =406, y =533
    x =33, y =381
    x =405, y =767
    x =13, y =883
    x =201, y =341
    x =593, y =991
    x =636, y =913
    x =508, y =782
    x =333, y =861
    x =306, y =863
    x =428, y =537
    x =373, y =775
    x =74, y =462
    x =196, y =299
    x =245, y =535
    x =312, y =993
    x =940, y =989
    x =12, y =708

but if the condition is changed to **x == y** from **x < y**, then the code
implicit lazy val genUnequalIntPairs = for {
      i <- Gen.choose(1,1000)
      j <- Gen.choose(1,1000)
      if (i < j)
    } yield {
      (i,j)
    }
    
    val kk = forAll(genUnequalIntPairs)  {
      case (x,y) => println("x =" + x + ", y =" + y)
        x == y
    }
    
    kk.check

produces
```
x =370, y =585
    x =0, y =585
    x =0, y =0
    x =0, y =293
    x =0, y =0
    x =0, y =147
    x =0, y =0
    x =0, y =74
    x =0, y =0
    x =0, y =37
    x =0, y =0
    x =0, y =19
    x =0, y =0
    x =0, y =10
    x =0, y =0
    x =0, y =5
    x =0, y =0
    x =0, y =3
```

**Comment by rickynils** [comment]
Your property fails, since `x != y`. ScalaCheck then tries to shrink the failing test case. That is why you get `(0,1)` (the minimal case that makes your property fail). You can see that ScalaCheck presents both the first failure and the minimal one.

If you fix your property so it doesn't fail, this "problem" will go away.
