### ISSUE TITLE
What implicits are needed for (Gen.oneOf("a", "b") |@| Gen.oneOf("a", "b"))(_+_)?

### ISSUE THREAD

**Issue by wpoosanguansit** [rickynils/scalacheck#255]
I do have an error stating that |@| is not a member of Arbitrary.   Thanks for any direction or hint as to what to import.  Appreciate your help.

**Comment by rickynils** [comment]
@wpoosanguansit I don't know what `|@|` is. It is not part of ScalaCheck.

**Comment by wpoosanguansit** [comment]
Seems like this is not relevant.  It's from applicative in cats.  Thanks.
