### ISSUE TITLE
Gen.choose not working as expected

### ISSUE THREAD

**Issue by alxest** [rickynils/scalacheck#260]
In below code, I expect x and y to pass assertion, but it fails. (x and y chosen from [0,8])
Is this intended behavior?
```
import org.scalacheck.Properties
import org.scalacheck.Prop.forAll
import org.scalacheck._

object PascalSpec extends Properties("pascal") {
  def pascal1(x: Int, y: Int): Int = {
    if(x == 0 || y == 0 || y == x) 1
    else pascal1(x-1, y) + pascal1(x-1, y-1)
  }

  def pascal2(x: Int, y: Int): Int = {
    def factorial(n: Int): Int =
      if(n == 0 || n == 1) 1 else factorial(n-1)
    factorial(x) / factorial(y) / factorial(x-y)
  }

  val smallIntPair = for {
    x <- Gen.choose(5, 8)
    y <- Gen.choose(5, 8)
  } yield (x, y)

  property("spec") = forAll(smallIntPair) {
    (n: (Int, Int)) => {
      val (x, y) = n
      println("{" + x + " " + y + "}")
      assert(5 <= x && x <= 8)
      assert(5 <= y && y <= 8)
      val ret = (pascal1(x,y) == pascal2(x,y))
      ret
    }
  }
}
```
Replacing       
```
val ret = (pascal1(x,y) == pascal2(x,y))
      ret
```
into 
```
true
```
makes assertion pass.
I am using scala 2.12.8 and I uploaded the code [here](https://github.com/alxest/scalacheck_question/blob/master/src/test/scala/test.scala). It should be reproducible.

**Comment by non** [comment]
Can you paste the output from the failing test/assertion?

**Comment by rickynils** [comment]
Your implementation (or property) seems to be wrong. See:

```
scala> def pascal1(x: Int, y: Int): Int = {
     |     if(x == 0 || y == 0 || y == x) 1
     |     else pascal1(x-1, y) + pascal1(x-1, y-1)
     |   }
pascal1: (x: Int, y: Int)Int

scala> def pascal2(x: Int, y: Int): Int = {
     |     def factorial(n: Int): Int =
     |       if(n == 0 || n == 1) 1 else factorial(n-1)
     |     factorial(x) / factorial(y) / factorial(x-y)
     |   }
pascal2: (x: Int, y: Int)Int

scala> pascal1(8,7)
res1: Int = 8

scala> pascal2(8,7)
res2: Int = 1
```

So, ScalaCheck correctly falsifies your property since `pascal1(8,7) != pascal2(8,7)`.

**Comment by alxest** [comment]
Yes, that is true.
What I was curious was why {0,7} and {0,0} is tested after that, even though I have chosen {x,y} from [5, 8] x [5, 8]. 
```
{8 7}
{0 7}
{0 0}
[info] ! pascal.spec: Exception raised on property evaluation.
[info] > ARG_0: (0,0)
[info] > ARG_0_ORIGINAL: (8,7)
```
Is this intended behavior? 
If so, I want to know more about the idea behind it. Is there written documentation about it?

**Comment by alxest** [comment]
@non 
Ah... Thanks for your reply. I might use *forAllNoShrink*.
I think it would be greater for user if test case minimaziton respects the *chosen* bound. (I am not sure if its implementation is easy or hard) Or if user can pass some valuation function (test input domain -> double) so that shrinking tries to find test data with maximized valuation.

**Comment by alxest** [comment]
I will close this issue, again thanks all!
