### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by informarte** [rickynils/scalacheck#265]
http://www.scalacheck.org/download.html states that ScalaCheck is relased under the 3-clause BSD license, but the file LICENSE does not contain the pure BSD 3-clause license: its first paragraph was taken from the ISC license. The resulting license may be equivalent to the original BSD 3-clause license but who knows ... Anyway, the webpage and the repository are inconsistent with regard to license information.

**Comment by rickynils** [comment]
Resolved in 6918ee8
