### ISSUE TITLE
posNum throws an IllegalBoundsError in 1.13.3-SNAPSHOT

### ISSUE THREAD

**Issue by ssanj** [rickynils/scalacheck#269]
If I run the following on scalacheck 1.13.2:

```
import org.scalacheck._
Prop.forAll(Gen.posNum[Int]) { n => n > 0 }.check
```

I get:
> + OK, passed 100 tests.

But with the 1.13.3-SNAPSHOT, I get:

> ! Exception raised on property evaluation.
> Exception: org.scalacheck.Gen$Choose$IllegalBoundsError: invalid bounds:
  low=1, high=0
> org.scalacheck.Gen$Choose$$anon$5.choose(Gen.scala:331)
> org.scalacheck.Gen$Choose$$anon$5.choose(Gen.scala:329)
> org.scalacheck.Gen$Choose$$anon$7.choose(Gen.scala:362)
> org.scalacheck.Gen$$anonfun$posNum$1.apply(Gen.scala:682)
> org.scalacheck.Gen$$anonfun$posNum$1.apply(Gen.scala:682)

Has some functionality changed around this area? Or am I incorrectly using posNum?

**Comment by non** [comment]
@ssanj Yes! Thanks for the bug report. I think I see what's going on.
