### ISSUE TITLE
Release for Scala 2.12.0

### ISSUE THREAD

**Issue by cheeseng** [rickynils/scalacheck#291]
Scala 2.12.0 is released, please kindly release ScalaCheck built for it.

Thank you.

**Comment by rickynils** [comment]
Will do, as soon as #290 is fixed (probably by just merging #294)

**Comment by rickynils** [comment]
I'll get to work releasing ScalaCheck 1.11 and 1.12 builds right away though.

**Comment by larsrh** [comment]
:+1: on releasing only a 1.13.4 for 2.12 with the fix incorporated

**Comment by rickynils** [comment]
I have released ScalaCheck 1.13.4 and 1.12.6 for Scala 2.12, 2.11 and 2.10, with the fix incorporated. I've also published a 2.12 build of ScalaCheck 1.11.6 (not fixed, and I don't know if it is affected)

**Comment by xuwei-k** [comment]
I could not find 1.13.x for Scala.js

https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_sjs0.6_2.12/

![screen shot 2016-11-02 at 5 04 58](https://cloud.githubusercontent.com/assets/389787/19905402/f1c0e6ce-a0b9-11e6-92a3-676dc8a7d385.png)

**Comment by rickynils** [comment]
@xuwei-k You're correct, it looks like I forgot publishing that build. On its way now!
