### ISSUE TITLE
Support "Otherwise" to be paired with "Whenever"

### ISSUE THREAD

**Issue by macalinao** [rickynils/scalacheck#297]
http://doc.scalatest.org/3.0.0/index.html#org.scalatest.prop.Whenever

It would be nice to do something like

```scala
whenever (cond) {
  // ...tests...
} otherwise {
  // ...more tests...
}
```

**Comment by non** [comment]
Did you mean to open this issue for ScalaTest?

**Comment by macalinao** [comment]
Yes.
