### ISSUE TITLE
Gen.listOfN fails for string for some property tests with function calls

### ISSUE THREAD

**Issue by dmyersturnbull** [rickynils/scalacheck#304]
This is a weird bug, but I can easily reproduce it.

#### this works

```scala
val gen = Gen.listOfN(6, Gen.alphaNumChar) map (_.mkString)
property("test") {
    forAll(gen) { (s: String) => {
        println(s.length) // always prints 6
        s should equal (s)
    }}
}
```

#### so does this (basically the same thing)

```scala
property(s"toHex(fromHex)) should be the identity") {
	forAll(gen) { (hexColor: String) => {
		println(hexColor.length) // always prints 6
		hexColor should equal (hexColor)
	}
}}
```

#### this doesn't

```scala
property(s"toHex(fromHex)) should be the identity") {
	forAll(gen) { (hexColor: String) => {
		println(hexColor.length) // prints 6, 3, 1, 0
		RgbColor.fromHex(hexColor).toHex should equal (hexColor)
	}
}}
```

The only difference is calling `RgbColor.fromHex(hexColor).toHex`

**Comment by dmyersturnbull** [comment]
I'm using Scala 2.11.8, scalatest and scalactic 3.0.0 with scalacheck 1.13.4 and scalamock-scalatest-support 3.2.2. Here's a [complete example](https://github.com/kokellab/kl-common-scala/blob/master/core/src/main/scala/kokellab/utils/core/addons/RgbColor.scala).

**Comment by rickynils** [comment]
@dmyersturnbull So what does ScalaCheck say about the property? Does it fail it? I assume that `RgbColor.fromHex(hexColor).toHex should equal (hexColor)` is false for some value of `hexColor`. ScalaCheck then tries to find a smaller version of `hexColor` that still falsifies the property.

**Comment by dmyersturnbull** [comment]
Yes, it fails because `RgbColor.fromHex` can only parse strings of length 6.

It seems that ScalaCheck shouldn't try to minimize a string in a way that violates the generator. Right?

**Comment by dmyersturnbull** [comment]
I should also add that the tests pass if I replace `RgbColor.fromHex(hexColor).toHex` with `String.valueOf(hexColor)`

**Comment by rickynils** [comment]
@dmyersturnbull ScalaCheck only tries to minimize when it has found an initial error. So there must be some string of length 6 that falsifies the property. ScalaCheck should inform you about both the initial failure case and the minimized one. But I can't vouch for ScalaTest, maybe it doesn't print the non-minimized failure case.

It is a known issue/feature that the minimization feature of ScalaCheck is not optimal, since it can go look for test cases that wasn't originally produced by the generator. But this **only** happens when the original generator actually triggered a failing property, so fixing the property (or the implementation) will remove the confusion.

**Comment by dmyersturnbull** [comment]
Thanks for helping, and of course for developing ScalaCheck. I guess there's no real bug here.

You're right: ScalaTest doesn't show the error as clearly as one would hope, and I didn't know that overly aggressive minimization was a limitation in ScalaCheck.

**Comment by non** [comment]
@dmyersturnbull One way that I tend to solve problems like this is by creating custom types to use in my properties. For example:

```scala
case class HexString(s: String)

object HexString {
  implicit val arbitiraryHexString: Arbitrary[HexString] =
    Arbitrary(arbitrary[Int].map { n =>
      val rgb = n & 0xffffff
      HexString("%06x" format rgb)
    })
}
```
