### ISSUE TITLE
A more typelevel themed logo

### ISSUE THREAD

**Issue by mgttlinger** [rickynils/scalacheck#306]
I suggest a more typelevel themed logo (at least for the stickers) which fits in with the general design and color scheme of the typelevel logo. One reason for that is that a black sticker looks not very good on a black laptop :wink:.
![scalacheck](https://cloud.githubusercontent.com/assets/5120487/20866133/28528902-ba25-11e6-90de-cd10066faf67.png)
This is my initial draft derived from the typelevel logo design by @killnicole. If there is interest at all we can go from here and make adjustments untill everybody is happy with the design.

**Comment by non** [comment]
@mgttlinger That's definitely nice-looking! I must confess that I secretly love having a black hexagon sticker on my laptop (but I don't oppose creating other stickers as well).

**Comment by mgttlinger** [comment]
Soooo, should I make any changes or send a vector graphic of it to anyone or wait for more objections or how does this move forward?

**Comment by rickynils** [comment]
@mgttlinger I'm sorry for my lack of feedback! To be honest I don't see the need for aligning ScalaCheck's logo with other Typelevel projects, and for the black-on-black problem I think we could just create inverted stickers (black font on white background).

**Comment by mgttlinger** [comment]
Ok, I can accept that.
