### ISSUE TITLE
Specifying the minimal number of test runs with SBT

### ISSUE THREAD

**Issue by anatoliykmetyuk** [rickynils/scalacheck#309]
I have the following under `src/test/scala/Suite.scala`:

```scala
object Suite extends Properties("Suite") {
  override def check(prms: Test.Parameters = Test.Parameters.default): Unit = {
    println("A")
    super.check(prms.withMinSuccessfulTests(1000))
  }

  override def main(args: Array[String]): Unit = {
    println("B")
    super.main(args)
  }
}
```

When I run it with `sbt test`, neither "A" nor "B" gets printed, and SBT executes only 100 tests for each property. How do I make it run 1000 tests instead?

**Comment by Philippus** [comment]
there's an example sbt project: https://github.com/rickynils/scalacheck/blob/master/examples/simple-sbt/build.sbt

**Comment by anatoliykmetyuk** [comment]
Thank you, this solves it.
