### ISSUE TITLE
release latest master

### ISSUE THREAD

**Issue by pjfanning** [rickynils/scalacheck#314]
Would it be possible to do a release from the current master code base?
I think getting a release of https://github.com/rickynils/scalacheck/pull/263 would be helpful.

**Comment by mdimjasevic** [comment]
Hi everyone!

I would also kindly ask you for a release that includes #263. This is a showstopper for test reproducibility via ScalaCheck. Furthermore, I'm working on adding support for ScalaCheck's `useSeed` in Specs2, but until ScalaCheck with this feature is released, I can't make progress there.

**Comment by ashawley** [comment]
This ticket was superseded by #374 which had a similar request.
