### ISSUE TITLE
Release 0.13.6

### ISSUE THREAD

**Issue by non** [rickynils/scalacheck#344]
I feel like the recent serialization issue warrants a new release, now that we have a fix in.

What do you think @rickynils?

I'm not sure I have Sonatype permissions to publish to `org.scalacheck` but if I do I'm happy to try to manage the release process.

**Comment by cquiroz** [comment]
It would be nice to get this out to support newer versions of scala.js added after the last release

**Comment by ttim** [comment]
`0.13.6` would be really nice for Summingbird project as well. We have issue with lambdas serialization and right now implemented workaround for that (not yet merged). Having working scalacheck release will help us to avoid this workaround at the first place.

**Comment by andreaTP** [comment]
Since recent addition of sjs 1.0.0-M1 support I wonder if we can have a release here

**Comment by rickynils** [comment]
This issue got stuck since we had to back-port stuff from master to the 1.13.x branch in order to maintain binary compatibility. I'm going to release the current master as 1.14.0 (#374), and close this issue. I hope people are fine with using 1.14.0 instead of 1.13.6.

**Comment by cquiroz** [comment]
Thanks, would you include scala.js-1.0 in the release? I guess we should update it to the latest M3 release

**Comment by cquiroz** [comment]
Nevermind. I see scalajs-1.0.0M3 is already in the list
