### ISSUE TITLE
release for Scala 2.13.0-M2, plz?

### ISSUE THREAD

**Issue by SethTisue** [rickynils/scalacheck#349]
now that 2.13.0-M2 is on Maven Central

**Comment by SethTisue** [comment]
@rickynils any chance you could turn the crank on this? the changes in M2 are modest, so there's a very good chance there won't be any hitches

**Comment by rickynils** [comment]
I've released ScalaCheck 1.12.6 and 1.13.5 for Scala 2.13.0-M2 now

**Comment by SethTisue** [comment]
thank you Rickard!
