### ISSUE TITLE
Gen.nonEmptyListOf...map generates empty list

### ISSUE THREAD

**Issue by AntonIvanov87** [rickynils/scalacheck#372]
```scala
import org.scalacheck.Gen
import org.scalacheck.Prop.forAll

object Main extends App {

  val charGen = Gen.oneOf('A', 'B')
  val charsGen = Gen.nonEmptyListOf(charGen)
  val stringGen = charsGen.map(_.mkString)

  forAll(stringGen) { (string: String) =>
    if (string.isEmpty) {
      throw new IllegalArgumentException("empty string!")
    }
    assert(false, "should see this message")
    true
  }.check

}
```
charsGen should generate non empty list of chars, that is why IllegalArgumenException("empty string!") should be never thown.
Unfortunately if an iteration fails, you see:
```
! Exception raised on property evaluation.
> ARG_0: ""
> ARG_0_ORIGINAL: "A"
> Exception: java.lang.IllegalArgumentException: empty string!
```
Empty string is very confusing, because it hides the real cause and contradicts with generator definition (nonEmptyListOf).

If you substitute stringGen with charsGen the output is correct:
```
! Exception raised on property evaluation.
> ARG_0: List(" ")
> ARG_0_ORIGINAL: List("B")
> Exception: java.lang.AssertionError: assertion failed: should see this me
  ssage
```
It looks like any map operation on a generator of lists causes this problem.

**Comment by ashawley** [comment]
You'd need to use `forAllNoShrink`.  

That constraints in generators aren't respected in shrinking is known issue, see #129.
