### ISSUE TITLE
1.14.0 release with useSeed

### ISSUE THREAD

**Issue by etorreborre** [rickynils/scalacheck#374]
@rickynils hi, can we please have a `0.14.0` release containing the possibility to set seeds on properties?

**Comment by mdimjasevic** [comment]
As a reminder, this was discussed and then merged with a pull request #263. @rickynils, can you please make a release including this?

**Comment by mdimjasevic** [comment]
Pretty please? @rickynils?

**Comment by mdimjasevic** [comment]
Just pinging to bring this up again. This would be a really useful feature to have.

**Comment by kantlove** [comment]
Agree with @mdimjasevic this is a super useful feature to have, @rickynils please release the latest master.

**Comment by idreeskhan** [comment]
Is there any update on this? @rickynils

**Comment by etorreborre** [comment]
@rickynils could you please tell us what you think about this issue? Is there anyone else besides you who can make some progress on this issue and others? (let it be clear that I'm not blaming you at all for not having open-source time!). We are currently discussing the possibility of forking ScalaCheck to support this functionality and make it accessible from specs2 but I think this should only be the last resort. Thanks :-)

cc/ @SethTisue, what do you propose in such a case?

**Comment by SethTisue** [comment]
let's discuss on #351

**Comment by rickynils** [comment]
@etorreborre I'm sorry for neglecting this request for so long. I'm going to try to release 1.14.0 as soon as possible. I'm basically just going to take the current master as it looks now, and release it. Are you fine with that, or is there anything else you think we should squeeze in?

**Comment by mdimjasevic** [comment]
It'd be great if you made a release with whatever is on the master branch. I've been waiting for the ability to set an initial seed, which is on the master branch.

If you could give an estimate on when the release is going to happen, that would be great; otherwise I'll continue with making a release based on an identical copy of ScalaCheck.

**Comment by etorreborre** [comment]
@rickynils that would be wonderful thanks @rickynils :-)

**Comment by rickynils** [comment]
@mdimjasevic I will try to get it out this weekend. The main issue is to somehow summarize the changelog since 1.13.5.

**Comment by mdimjasevic** [comment]
@rickynils , I'm looking forward to the release!

**Comment by rickynils** [comment]
ScalaCheck 1.14.0 has been released, with builds for Scala 2.10, 2.11, 2.12 and 2.13-M3. There are also builds for ScalaJS 0.6.22 and 1.0.0-M3 available.

**Comment by mdimjasevic** [comment]
@rickynils thank you a lot for the release!
