### ISSUE TITLE
publish for Scala 2.13.0-M3, please?

### ISSUE THREAD

**Issue by SethTisue** [rickynils/scalacheck#382]
ScalaCheck's in the hot seat, as usual!

![image1](https://user-images.githubusercontent.com/161079/35659166-aaabf1a4-06b9-11e8-88b4-63e5fc3d044c.jpeg)

2.13.0-M3 release notes: https://github.com/scala/scala/releases/tag/v2.13.0-M3

**Comment by rickynils** [comment]
@SethTisue I've published Scala 2.13.0-M3 builds of ScalaCheck 1.12.6 and 1.13.5 now. Only JVM builds for now, as ScalaJS doesn't seem to have M3 builds.

**Comment by gourlaysama** [comment]
@rickynils you need to update ScalaJS to 0.6.22 to get the 2.13.0-M3 support, the previous versions will not have builds for M3.

**Comment by ashawley** [comment]
Maybe merge #38 and then take the opportunity to cut a new release, 1.14.0?  This will give a 2.13.0-M3 build for scalajs.

**Comment by SethTisue** [comment]
@rickynils thanks for the publish... it seems to be working in the projects I've tried it in. Scala.js support is pretty important though — Scala.js is practically ubiquitous now in the library ecosystem

**Comment by rickynils** [comment]
I'll see if bumping ScalaJS to 0.6.22 works now. It didn't work first time I tried, because there were no M3 build available.

**Comment by rickynils** [comment]
@SethTisue Scala 2.13.0-M3 builds of ScalaCheck 1.12.6 and 1.13.5 for ScalaJS have been published now.

**Comment by SethTisue** [comment]
wonderful, thank you!
