### ISSUE TITLE
Need a way to combine independent generators

### ISSUE THREAD

**Issue by morgen-peschke** [rickynils/scalacheck#389]
The usual way to compose generators is with `flatMap` and `map`, which covers most use cases, unless you're using something like `Gen.listOfN` to produce a series data.

Assuming a generator for tags:
```scala
val tagGen: Gen[Tag] = 
  for {
    name <- Gen.identifier
    value <- Gen.alphaStr
  } yield Tag(name, value)
```

Or the equivalent:
```scala
val tagGen: Gen[Tag] = Gen.zip(Gen.identifier, Gen.alphaStr).map(Tag.tupled)
```

Generating a list using `Gen.listOf(tagGen)` tends to produce a high number of cases where all of the tag names are the same. As I understand it, this is because `Gen.flatMap` sequences the values and the full distribution is only really seen in the last `Gen`.

What I'm looking for, and have not seen how to do this is the docs or source, is something like this:
```scala
Gen.product(Gen.identifier, Gen.alphaStr).map(Tag.tupled)
```
Which would sample equally from `Gen`s which are passed to it.

**Comment by ashawley** [comment]
> As I understand it, this is because `Gen.flatMap` sequences the values and the full distribution is only really seen in the last `Gen`.

I'm afraid you may be misunderstanding the semantics of generators.   You're confusion is probably caused by a defect in the underlying `Gen.pick` method of Scalacheck, see #333.  The fix isn't released, yet, though.  The `Gen.identifier` and `Gen.alphaStr` generators are implemented with`Gen.choose` and that in turn uses `Gen.pick`.  That could explain the duplication and the poor distribution of values you're seeing.

**Comment by morgen-peschke** [comment]
That's possible, however the other noticeable place I've seen this behavior is with `Gen.uuid`, which uses `Gen.choose[Long]`. I've traced that one back and it doesn't _look_ like it's using `Gen.pick`, though I could be wrong about that one.

I'll see if I can bang together a simplified test case for this over the weekend.

**Comment by ashawley** [comment]
That is true that `Gen.choose` doesn't use `Gen.pick`, so it wouldn't suffer from the defect I mentioned earlier in this case.   I was mistaken.   

It would be interesting to know if there was a distribution problem with of `Gen.uuid` or better `Gen.choose[Long]`.  You should try to distill your issue in a test, for example:

```scala
    val pairGen: Gen[(Long, Char)] = for {
      x <- Gen.choose(0L, 1L)
      a <- Gen.choose('a', 'b')
    } yield {
      (x, a)
    }
    
    val pairsGen = Gen.listOfN(2, pairGen)
    
    property("pairsGen") = {
      Prop.forAll(pairsGen) { x =>
        Prop.collect(x.map(_.toString).mkString(" ")) {
          Prop.passed
        }
      }
    }
```

Would produce:

    > Collected test data: 
    13% (0,a) (1,b)
    8% (1,b) (1,a)
    8% (0,b) (0,b)
    7% (1,b) (0,a)
    7% (0,b) (1,a)
    7% (1,a) (0,a)
    7% (0,a) (0,a)
    6% (0,a) (1,a)
    6% (0,b) (0,a)
    6% (1,a) (1,a)
    6% (0,b) (1,b)
    5% (1,b) (1,b)
    5% (0,a) (0,b)
    4% (1,b) (0,b)
    3% (1,a) (1,b)
    2% (1,a) (0,b)

**Comment by morgen-peschke** [comment]
Sort of good news: I was unable to reproduce the issue, so `Gen.uuid` is likely fine.

If I see it again I'll try and pull out a minimal example and reopen, but for now I'm going to close.
