### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by erikerlandson** [rickynils/scalacheck#437]
scalacheck (and scalacheck for scala js) for Scala 2.13.0-M5 seem to be on the critical path for a variety of projects updating to 2.13.0-M5

**Comment by ashawley** [comment]
A few hours ago, Scalajs was published in #435:

http://central.maven.org/maven2/org/scalacheck/scalacheck_sjs0.6_2.13.0-M5/1.14.0/

**Comment by SethTisue** [comment]
@rickynils this issue can be closed now
