### ISSUE TITLE
Gen.posNum never creates numbers < 1

### ISSUE THREAD

**Issue by estsauver** [rickynils/scalacheck#439]
The Gen.posNum generator doesn't create numbers less than the "one" of the Numeric that's defined. 

https://github.com/rickynils/scalacheck/blob/master/src/main/scala/org/scalacheck/Gen.scala#L800

Would you appreciate a patch that adds a zero as a min bound and filters the zero out to ensure it's still positive?

**Comment by ashawley** [comment]
Sounds like a bug to me.  A pull request with tests would probably help study and discuss the issue further.

> Would you appreciate a patch that adds a zero as a min bound and filters the zero out to ensure it's still positive?

Since `Gen.choose` is an inclusive range generator and there isn't an exclusive alternative in ScalaCheck, it seems that filtering out zero sounds like the only way to fix this.
