### ISSUE TITLE
Issue with output of Generator

### ISSUE THREAD

**Issue by geojolly** [rickynils/scalacheck#452]
I have something like this:
val vowel = Gen.oneOf('A', 'E', 'I', 'O', 'U', 'Y')
println("vowel")

and it prints **org.scalacheck.Gen$$anon$3@6e256cb** 

What is the reason for this ?

**Comment by ashawley** [comment]
You need to use `vowel.sample`.

The [User Guide](https://github.com/rickynils/scalacheck/blob/master/doc/UserGuide.md) should introduce`sample` sooner to avoid this confusion.

**Comment by geojolly** [comment]
Just a followup, 
imagine something like this 
val vowel: Gen[String] = Gen.Frequency ( 2 -> "A", 1 -> "E") 
println(vowel.sample)

It will print : **Some(A)** 
though I expect **"A"**  (as vowel is Gen[String] not Some[x])
