### ISSUE TITLE
Iterable List of String for Gen.frequency

### ISSUE THREAD

**Issue by geojolly** [rickynils/scalacheck#454]
I have : 
val x : Iterable[List[String]]    // Something like List[2,"aaa"], List[3"xxx"] 
I also have a method that deconstructs the List to create a tuple (frequency, string)
Is there a way that Gen.frequency could take this as input ?
something like - 
_val temp : Gen[String] = Gen.frequency (
 while(x.hasNext) { deconstruc(x.next()) 
)_
Using iterator raises issues as for or while loop by default to have **Unit** as return type while Gen.frequency requires (Int, String)

**Comment by ashawley** [comment]
Since `Gen.frequency` is a varargs method, you can expand your sequence of values to the arguments with `_: *`:

```scala
val strFreqs = List(2 -> "aaa", 3 -> "xxx")
val genFreqs: Iterable[(Int, Gen[String])] =
  for {
    (i, str) <- strFreqs
  } yield {
    i -> Gen.const(str)
  }
property("genFreqs") = {
  Prop.forAll(Gen.frequency(genFreqs.toSeq: _*)) { s: String =>
    ...
```

**Comment by geojolly** [comment]
Hello, it works well and Thanks a lot for the comment 

But, just another question.
 
What if I want to have something like : 
Gen.frequency((genFreqs.toSeq: _*), (2,"3")) ie. you have from list plus+ other tuple that need to be integrated. )

It seems not possible at the moment ;)

**Comment by ashawley** [comment]
I'm not a varargs expert, but you can just append another tuple with `:+`.  For your example,

```scala
Prop.forAll(Gen.frequency(genFreqs.toSeq :+ 2 -> Gen.const("3"): _*)) { s: String =>
```

**Comment by geojolly** [comment]
@ashawley  Yeah thanks :)
