### ISSUE TITLE
Publish 2.13.0

### ISSUE THREAD

**Issue by ashawley** [rickynils/scalacheck#480]
Once 1.14.0 for 2.13 is published, #479 will be green in Travis for the master branch.

This may be a good time to publish Scalajs 1.0.0-M8 for 2.13 and 2.12 from the `1.14.0_sonatype` branch, as well, which would require #475.

**Comment by ashawley** [comment]
Tried helping with this along with PR #481.

**Comment by dwijnand** [comment]
Fixed with https://github.com/rickynils/scalacheck/pull/481.

**Comment by xuwei-k** [comment]
🎉 

- https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/
- https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs0.6_2.13/
