### ISSUE TITLE
mapOfN will not work well if there is a high probability of duplicate keys

### ISSUE THREAD

**Issue by alexeyr** [rickynils/scalacheck#89]
`mapOfN` generates exactly `n` key-value pairs, constructs a map from them, and checks that the size is `n`. This will fail and be discarded if there are any duplicate keys. Given that, e.g. numeric generators produce specific values with high probability, this is quite likely to happen.

**Comment by gkazior** [comment]
I got similar problem with:

```scala
Gen.containerOfN[Set, String](2, Gen.oneOf("one", "two"))
```
which usually returns Set(one, two) but sometimes Set() 
Unfortunately my case was much more complicated.

The documentation states: 
"The size of the generated container is given by n."
Which is not true!

```scala
val gen=Gen.containerOfN[Set, String](2, Gen.oneOf("one", "two")).suchThat(_.size == 2)
gen.sample
```

I understand the problem with:
```scala
Gen.containerOfN[Set, String](3, Gen.oneOf("one", "two"))
```

BTW. I wanted a list with unique elements and given length. Possibly there is a better method.

Great lib!
